FROM wordpress:latest

# Install Composer
COPY --from=composer /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

# Install Codeception
RUN set -eux; \
    cd /usr/src/wordpress; \
    /usr/bin/composer require "codeception/codeception" --dev;

# Create configuration file for configuration test.
# We use a special suite to be able to use the most common suites in the future
RUN set -eux; \
    cd /usr/src/wordpress; \
    php vendor/bin/codecept bootstrap; \
    php vendor/bin/codecept g:suite init_config; \
    php vendor/bin/codecept generate:cest init_config initConfig;

# Copy the configuration file of suite
COPY codeception/init_config.suite.yml tests/init_config.suite.yml

# Copy the test file
COPY codeception/initConfigCest.php tests/init_config/initConfigCest.php

# Run codeception suite
RUN set -eux; \
    cd /usr/src/wordpress; \
    php vendor/bin/codecept build; \
    php vendor/bin/codecept run init_config;